/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Riyan
 */
public class MainForm extends javax.swing.JFrame
{

    /**
     * Creates new form MainForm
     */
    public MainForm()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        appTitleText = new javax.swing.JLabel();
        About = new javax.swing.JLabel();
        setTimeText = new javax.swing.JLabel();
        hoursTextField = new javax.swing.JTextField();
        minsTextField = new javax.swing.JTextField();
        secTextField = new javax.swing.JTextField();
        isForceCheck = new javax.swing.JCheckBox();
        ActsComBox = new javax.swing.JComboBox();
        doActionButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Windows Shutdown Schedule");
        setResizable(false);

        appTitleText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        appTitleText.setForeground(new java.awt.Color(102, 0, 102));
        appTitleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appTitleText.setText("Windows Shutdown Schedule");

        About.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        About.setForeground(new java.awt.Color(102, 0, 102));
        About.setText("About");
        About.setToolTipText("About Program And Information To Use ");
        About.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        About.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                AboutMouseClicked(evt);
            }
        });

        setTimeText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        setTimeText.setForeground(new java.awt.Color(102, 0, 102));
        setTimeText.setText("Set Time ");

        hoursTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hoursTextField.setToolTipText("When Do Action <in Hours>");

        minsTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        minsTextField.setToolTipText("When Do Action <in Minutes>");

        secTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        secTextField.setToolTipText("When Do Action <in Seconds>");

        isForceCheck.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        isForceCheck.setForeground(new java.awt.Color(102, 0, 102));
        isForceCheck.setText("Force Action");
        isForceCheck.setToolTipText("Force Action Or Not...\nWARNING : Force Enabled will force action,so save your works beforce enabling force option !");

        ActsComBox.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ActsComBox.setForeground(new java.awt.Color(102, 0, 102));
        ActsComBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Shutdown", "Restart", "Abort Action" }));
        ActsComBox.setToolTipText("Choose Shutdown Mode");
        ActsComBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ChangeShutAct(evt);
            }
        });

        doActionButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        doActionButton.setForeground(new java.awt.Color(102, 0, 102));
        doActionButton.setText("Shutdown Now");
        doActionButton.setToolTipText("Do Action");
        doActionButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                doActionButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Hours");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Minutes");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Seconds");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(isForceCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doActionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(appTitleText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(About))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(hoursTextField)
                                    .addComponent(setTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(minsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(secTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ActsComBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appTitleText)
                    .addComponent(About))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setTimeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ActsComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isForceCheck)
                    .addComponent(doActionButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChangeShutAct(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ChangeShutAct
    {//GEN-HEADEREND:event_ChangeShutAct
        // TODO add your handling code here:
        if (ActsComBox.getSelectedItem() == "Shutdown")
        {
            doActionButton.setText("Shutdown Now");
        }
        else if (ActsComBox.getSelectedItem() == "Restart")
        {
            doActionButton.setText("Restart Now");
        }
        else if (ActsComBox.getSelectedItem() == "Abort Action")
        {
            doActionButton.setText("Abort Action Now");
        }
    }//GEN-LAST:event_ChangeShutAct

    private void doActionButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_doActionButtonActionPerformed
    {//GEN-HEADEREND:event_doActionButtonActionPerformed
        // TODO add your handling code here:
        Executor exe=new Executor();
        exe.doShutAct(hoursTextField.getText(), minsTextField.getText(), secTextField.getText(), isForceCheck.isSelected(), ActsComBox.getSelectedItem().toString());
    }//GEN-LAST:event_doActionButtonActionPerformed

    private void AboutMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_AboutMouseClicked
    {//GEN-HEADEREND:event_AboutMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Windows Shutdown Scheduler\nVersion 0.0.1\n2015\n\nAuthor :\nRiyan Saputra Irawan\nriyansaputrai007@gmail.com");
    }//GEN-LAST:event_AboutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainForm().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About;
    private javax.swing.JComboBox ActsComBox;
    private javax.swing.JLabel appTitleText;
    private javax.swing.JButton doActionButton;
    protected javax.swing.JTextField hoursTextField;
    private javax.swing.JCheckBox isForceCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    protected javax.swing.JTextField minsTextField;
    protected javax.swing.JTextField secTextField;
    private javax.swing.JLabel setTimeText;
    // End of variables declaration//GEN-END:variables
}
